/**
 * Pave360 VAS Dedicated Backend Endpoint Paths
 * Used to communicate directly with VITE_VAS_API_URL
 */
export const VAS_PATHS = {
  auth: {
    login: "/api/v1/auth/login",
    logout: "/api/v1/auth/logout",
    me: "/api/v1/auth/me",
    changePassword: "/api/v1/auth/change-password",
  },
  dashboard: {
    overview: "/api/v1/dashboard",
    metrics: "/api/v1/dashboard",
    carrierStatus: "/api/v1/dashboard",
    recentActivity: "/api/v1/dashboard",
  },
  messaging: {
    list: "/api/v1/messages",
    send: "/api/v1/messages",
    detail: (id: string) => `/api/v1/messages/${id}`,
    bulk: "/api/v1/messages/bulk",
    upload: "/api/v1/messages/upload",
    uploadStatus: (jobId: string) => `/api/v1/messages/upload/${jobId}`,
  },
  delivery: {
    reports: "/api/v1/delivery-reports",
    inbound: "/api/v1/inbound",
  },
  ussd: {
    center: "/api/v1/ussd/center",
    notify: "/api/v1/ussd/notify",
    sessions: "/api/v1/ussd/sessions",
    sessionDetail: (id: string) => `/api/v1/ussd/sessions/${id}`,
  },
  network: {
    carriers: "/api/v1/carriers",
    carrier: (id: string) => `/api/v1/carriers/${id}`,
    connections: "/api/v1/connections",
    connection: (id: string) => `/api/v1/connections/${id}`,
    toggleConnection: (id: string) => `/api/v1/connections/${id}/toggle`,
    reconnectConnection: (id: string) => `/api/v1/connections/${id}/reconnect`,
    testConnection: (id: string) => `/api/v1/connections/${id}/test`,
    routes: "/api/v1/routes",
    route: (id: string) => `/api/v1/routes/${id}`,
    toggleRoute: (id: string) => `/api/v1/routes/${id}/toggle`,
    simulateRoute: "/api/v1/routes/simulate",
    workers: "/api/v1/queues",
    queues: "/api/v1/queues",
    queueMetrics: "/api/v1/queues",
    smppStatus: "/api/v1/smpp-server/status",
    smppDisconnect: (sessionId: string) => `/api/v1/smpp-server/disconnect/${sessionId}`,
    smppSessions: "/api/v1/smpp-server/status",
    dropSmppSession: (id: string) => `/api/v1/smpp-server/disconnect/${id}`,
  },
  traffic: {
    messages: "/api/v1/messages",
    messageDetail: (id: string) => `/api/v1/messages/${id}`,
    dlr: "/api/v1/delivery-reports",
    senderIds: "/api/v1/senders",
    inboundMo: "/api/v1/inbound",
    ussd: "/api/v1/ussd/sessions",
    ussdSend: "/api/v1/ussd/notify",
  },
  operations: {
    monitoring: "/api/v1/dashboard",
    alarms: "/api/v1/logs/audit",
    acknowledgeAlarm: (id: string) => `/api/v1/logs/audit/${id}`,
    resolveAlarm: (id: string) => `/api/v1/logs/audit/${id}`,
  },
  admin: {
    tenants: "/api/v1/tenants",
    tenant: (id: string) => `/api/v1/tenants/${id}`,
    users: "/api/v1/users",
    user: (id: string) => `/api/v1/users/${id}`,
    toggleUserStatus: (id: string) => `/api/v1/users/${id}/toggle-status`,
    roles: "/api/v1/roles",
    role: (id: string) => `/api/v1/roles/${id}`,
    rolePermissions: (id: string) => `/api/v1/roles/${id}/permissions`,
    auditLogs: "/api/v1/logs/audit",
  },
  developers: {
    keys: "/api/v1/settings",
    revokeKey: (id: string) => `/api/v1/settings/${id}`,
    webhooks: "/api/v1/webhooks",
    webhook: (id: string) => `/api/v1/webhooks/${id}`,
    deleteWebhook: (id: string) => `/api/v1/webhooks/${id}`,
    testWebhook: (id: string) => `/api/v1/webhooks/${id}/ping`,
    webhookDeliveries: (id: string) => `/api/v1/webhooks/${id}/deliveries`,
    logs: "/api/v1/logs/api",
  },
  settings: {
    system: "/api/v1/settings",
    systemSetting: (id: string) => `/api/v1/settings/${id}`,
  },
  reports: {
    messaging: "/api/v1/reports/messaging",
    delivery: "/api/v1/reports/delivery",
    financial: "/api/v1/reports/financial",
    billing: "/api/v1/reports/financial",
    carrierTelemetry: "/api/v1/reports/delivery",
  },
} as const
