/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard/alerts'
import { Route as DashboardApiKeysRouteImport } from './routes/_dashboard/api-keys'
import { Route as DashboardAuditRouteImport } from './routes/_dashboard/audit'
import { Route as DashboardAuditLogsRouteImport } from './routes/_dashboard/audit-logs'
import { Route as DashboardCarriersRouteImport } from './routes/_dashboard/carriers'
import { Route as DashboardConnectionsRouteImport } from './routes/_dashboard/connections'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardDeliveryReportsRouteImport } from './routes/_dashboard/delivery-reports'
import { Route as DashboardInboundRouteImport } from './routes/_dashboard/inbound'
import { Route as DashboardMessagesRouteImport } from './routes/_dashboard/messages'
import { Route as DashboardMonitoringRouteImport } from './routes/_dashboard/monitoring'
import { Route as DashboardQueuesRouteImport } from './routes/_dashboard/queues'
import { Route as DashboardReportsRouteImport } from './routes/_dashboard/reports'
import { Route as DashboardRolesRouteImport } from './routes/_dashboard/roles'
import { Route as DashboardRoutingRouteImport } from './routes/_dashboard/routing'
import { Route as DashboardSendersRouteImport } from './routes/_dashboard/senders'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardSmppServerRouteImport } from './routes/_dashboard/smpp-server'
import { Route as DashboardSwaggerRouteImport } from './routes/_dashboard/swagger'
import { Route as DashboardTenantsRouteImport } from './routes/_dashboard/tenants'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard/users'
import { Route as DashboardUssdRouteImport } from './routes/_dashboard/ussd'
import { Route as DashboardWebhooksRouteImport } from './routes/_dashboard/webhooks'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as DashboardAdministrationRolesRouteImport } from './routes/_dashboard/administration.roles'
import { Route as DashboardAdministrationTenantsRouteImport } from './routes/_dashboard/administration.tenants'
import { Route as DashboardAdministrationUsersRouteImport } from './routes/_dashboard/administration.users'
import { Route as DashboardDevelopersApiKeysRouteImport } from './routes/_dashboard/developers.api-keys'
import { Route as DashboardDevelopersDocumentationRouteImport } from './routes/_dashboard/developers.documentation'
import { Route as DashboardDevelopersLogsRouteImport } from './routes/_dashboard/developers.logs'
import { Route as DashboardDevelopersWebhooksRouteImport } from './routes/_dashboard/developers.webhooks'
import { Route as DashboardNetworkCarriersRouteImport } from './routes/_dashboard/network.carriers'
import { Route as DashboardNetworkConnectionsRouteImport } from './routes/_dashboard/network.connections'
import { Route as DashboardNetworkQueuesRouteImport } from './routes/_dashboard/network.queues'
import { Route as DashboardNetworkRoutingRouteImport } from './routes/_dashboard/network.routing'
import { Route as DashboardNetworkSmppServerRouteImport } from './routes/_dashboard/network.smpp-server'
import { Route as DashboardOperationsAlarmsRouteImport } from './routes/_dashboard/operations.alarms'
import { Route as DashboardOperationsMonitoringRouteImport } from './routes/_dashboard/operations.monitoring'
import { Route as DashboardTrafficDeliveryReportsRouteImport } from './routes/_dashboard/traffic.delivery-reports'
import { Route as DashboardTrafficInboundMoRouteImport } from './routes/_dashboard/traffic.inbound-mo'
import { Route as DashboardTrafficLogsRouteImport } from './routes/_dashboard/traffic.logs'
import { Route as DashboardTrafficReportsBillingRouteImport } from './routes/_dashboard/traffic.reports-billing'
import { Route as DashboardTrafficSenderIdsRouteImport } from './routes/_dashboard/traffic.sender-ids'
import { Route as DashboardTrafficUssdSessionsRouteImport } from './routes/_dashboard/traffic.ussd-sessions'
import { Route as DashboardUssdNotifyRouteImport } from './routes/_dashboard/ussd.notify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogsRoute = DashboardAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCarriersRoute = DashboardCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectionsRoute = DashboardConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeliveryReportsRoute =
  DashboardDeliveryReportsRouteImport.update({
    id: '/delivery-reports',
    path: '/delivery-reports',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInboundRoute = DashboardInboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueuesRoute = DashboardQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoutingRoute = DashboardRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSendersRoute = DashboardSendersRouteImport.update({
  id: '/senders',
  path: '/senders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmppServerRoute = DashboardSmppServerRouteImport.update({
  id: '/smpp-server',
  path: '/smpp-server',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSwaggerRoute = DashboardSwaggerRouteImport.update({
  id: '/swagger',
  path: '/swagger',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTenantsRoute = DashboardTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUssdRoute = DashboardUssdRouteImport.update({
  id: '/ussd',
  path: '/ussd',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DashboardRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdministrationRolesRoute =
  DashboardAdministrationRolesRouteImport.update({
    id: '/administration/roles',
    path: '/administration/roles',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdministrationTenantsRoute =
  DashboardAdministrationTenantsRouteImport.update({
    id: '/administration/tenants',
    path: '/administration/tenants',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdministrationUsersRoute =
  DashboardAdministrationUsersRouteImport.update({
    id: '/administration/users',
    path: '/administration/users',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDevelopersApiKeysRoute =
  DashboardDevelopersApiKeysRouteImport.update({
    id: '/developers/api-keys',
    path: '/developers/api-keys',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDevelopersDocumentationRoute =
  DashboardDevelopersDocumentationRouteImport.update({
    id: '/developers/documentation',
    path: '/developers/documentation',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDevelopersLogsRoute = DashboardDevelopersLogsRouteImport.update({
  id: '/developers/logs',
  path: '/developers/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevelopersWebhooksRoute =
  DashboardDevelopersWebhooksRouteImport.update({
    id: '/developers/webhooks',
    path: '/developers/webhooks',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardNetworkCarriersRoute =
  DashboardNetworkCarriersRouteImport.update({
    id: '/network/carriers',
    path: '/network/carriers',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardNetworkConnectionsRoute =
  DashboardNetworkConnectionsRouteImport.update({
    id: '/network/connections',
    path: '/network/connections',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardNetworkQueuesRoute = DashboardNetworkQueuesRouteImport.update({
  id: '/network/queues',
  path: '/network/queues',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNetworkRoutingRoute = DashboardNetworkRoutingRouteImport.update({
  id: '/network/routing',
  path: '/network/routing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNetworkSmppServerRoute =
  DashboardNetworkSmppServerRouteImport.update({
    id: '/network/smpp-server',
    path: '/network/smpp-server',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOperationsAlarmsRoute =
  DashboardOperationsAlarmsRouteImport.update({
    id: '/operations/alarms',
    path: '/operations/alarms',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOperationsMonitoringRoute =
  DashboardOperationsMonitoringRouteImport.update({
    id: '/operations/monitoring',
    path: '/operations/monitoring',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTrafficDeliveryReportsRoute =
  DashboardTrafficDeliveryReportsRouteImport.update({
    id: '/traffic/delivery-reports',
    path: '/traffic/delivery-reports',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTrafficInboundMoRoute =
  DashboardTrafficInboundMoRouteImport.update({
    id: '/traffic/inbound-mo',
    path: '/traffic/inbound-mo',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTrafficLogsRoute = DashboardTrafficLogsRouteImport.update({
  id: '/traffic/logs',
  path: '/traffic/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrafficReportsBillingRoute =
  DashboardTrafficReportsBillingRouteImport.update({
    id: '/traffic/reports-billing',
    path: '/traffic/reports-billing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTrafficSenderIdsRoute =
  DashboardTrafficSenderIdsRouteImport.update({
    id: '/traffic/sender-ids',
    path: '/traffic/sender-ids',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTrafficUssdSessionsRoute =
  DashboardTrafficUssdSessionsRouteImport.update({
    id: '/traffic/ussd-sessions',
    path: '/traffic/ussd-sessions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardUssdNotifyRoute = DashboardUssdNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => DashboardUssdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/alerts': typeof DashboardAlertsRoute
  '/api-keys': typeof DashboardApiKeysRoute
  '/audit': typeof DashboardAuditRoute
  '/audit-logs': typeof DashboardAuditLogsRoute
  '/carriers': typeof DashboardCarriersRoute
  '/connections': typeof DashboardConnectionsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/delivery-reports': typeof DashboardDeliveryReportsRoute
  '/inbound': typeof DashboardInboundRoute
  '/messages': typeof DashboardMessagesRoute
  '/monitoring': typeof DashboardMonitoringRoute
  '/queues': typeof DashboardQueuesRoute
  '/reports': typeof DashboardReportsRoute
  '/roles': typeof DashboardRolesRoute
  '/routing': typeof DashboardRoutingRoute
  '/senders': typeof DashboardSendersRoute
  '/settings': typeof DashboardSettingsRoute
  '/smpp-server': typeof DashboardSmppServerRoute
  '/swagger': typeof DashboardSwaggerRoute
  '/tenants': typeof DashboardTenantsRoute
  '/users': typeof DashboardUsersRoute
  '/ussd': typeof DashboardUssdRouteWithChildren
  '/webhooks': typeof DashboardWebhooksRoute
  '/account/login': typeof AccountLoginRoute
  '/administration/roles': typeof DashboardAdministrationRolesRoute
  '/administration/tenants': typeof DashboardAdministrationTenantsRoute
  '/administration/users': typeof DashboardAdministrationUsersRoute
  '/developers/api-keys': typeof DashboardDevelopersApiKeysRoute
  '/developers/documentation': typeof DashboardDevelopersDocumentationRoute
  '/developers/logs': typeof DashboardDevelopersLogsRoute
  '/developers/webhooks': typeof DashboardDevelopersWebhooksRoute
  '/network/carriers': typeof DashboardNetworkCarriersRoute
  '/network/connections': typeof DashboardNetworkConnectionsRoute
  '/network/queues': typeof DashboardNetworkQueuesRoute
  '/network/routing': typeof DashboardNetworkRoutingRoute
  '/network/smpp-server': typeof DashboardNetworkSmppServerRoute
  '/operations/alarms': typeof DashboardOperationsAlarmsRoute
  '/operations/monitoring': typeof DashboardOperationsMonitoringRoute
  '/traffic/delivery-reports': typeof DashboardTrafficDeliveryReportsRoute
  '/traffic/inbound-mo': typeof DashboardTrafficInboundMoRoute
  '/traffic/logs': typeof DashboardTrafficLogsRoute
  '/traffic/reports-billing': typeof DashboardTrafficReportsBillingRoute
  '/traffic/sender-ids': typeof DashboardTrafficSenderIdsRoute
  '/traffic/ussd-sessions': typeof DashboardTrafficUssdSessionsRoute
  '/ussd/notify': typeof DashboardUssdNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/alerts': typeof DashboardAlertsRoute
  '/api-keys': typeof DashboardApiKeysRoute
  '/audit': typeof DashboardAuditRoute
  '/audit-logs': typeof DashboardAuditLogsRoute
  '/carriers': typeof DashboardCarriersRoute
  '/connections': typeof DashboardConnectionsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/delivery-reports': typeof DashboardDeliveryReportsRoute
  '/inbound': typeof DashboardInboundRoute
  '/messages': typeof DashboardMessagesRoute
  '/monitoring': typeof DashboardMonitoringRoute
  '/queues': typeof DashboardQueuesRoute
  '/reports': typeof DashboardReportsRoute
  '/roles': typeof DashboardRolesRoute
  '/routing': typeof DashboardRoutingRoute
  '/senders': typeof DashboardSendersRoute
  '/settings': typeof DashboardSettingsRoute
  '/smpp-server': typeof DashboardSmppServerRoute
  '/swagger': typeof DashboardSwaggerRoute
  '/tenants': typeof DashboardTenantsRoute
  '/users': typeof DashboardUsersRoute
  '/ussd': typeof DashboardUssdRouteWithChildren
  '/webhooks': typeof DashboardWebhooksRoute
  '/account/login': typeof AccountLoginRoute
  '/administration/roles': typeof DashboardAdministrationRolesRoute
  '/administration/tenants': typeof DashboardAdministrationTenantsRoute
  '/administration/users': typeof DashboardAdministrationUsersRoute
  '/developers/api-keys': typeof DashboardDevelopersApiKeysRoute
  '/developers/documentation': typeof DashboardDevelopersDocumentationRoute
  '/developers/logs': typeof DashboardDevelopersLogsRoute
  '/developers/webhooks': typeof DashboardDevelopersWebhooksRoute
  '/network/carriers': typeof DashboardNetworkCarriersRoute
  '/network/connections': typeof DashboardNetworkConnectionsRoute
  '/network/queues': typeof DashboardNetworkQueuesRoute
  '/network/routing': typeof DashboardNetworkRoutingRoute
  '/network/smpp-server': typeof DashboardNetworkSmppServerRoute
  '/operations/alarms': typeof DashboardOperationsAlarmsRoute
  '/operations/monitoring': typeof DashboardOperationsMonitoringRoute
  '/traffic/delivery-reports': typeof DashboardTrafficDeliveryReportsRoute
  '/traffic/inbound-mo': typeof DashboardTrafficInboundMoRoute
  '/traffic/logs': typeof DashboardTrafficLogsRoute
  '/traffic/reports-billing': typeof DashboardTrafficReportsBillingRoute
  '/traffic/sender-ids': typeof DashboardTrafficSenderIdsRoute
  '/traffic/ussd-sessions': typeof DashboardTrafficUssdSessionsRoute
  '/ussd/notify': typeof DashboardUssdNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/_dashboard/alerts': typeof DashboardAlertsRoute
  '/_dashboard/api-keys': typeof DashboardApiKeysRoute
  '/_dashboard/audit': typeof DashboardAuditRoute
  '/_dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/_dashboard/carriers': typeof DashboardCarriersRoute
  '/_dashboard/connections': typeof DashboardConnectionsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/delivery-reports': typeof DashboardDeliveryReportsRoute
  '/_dashboard/inbound': typeof DashboardInboundRoute
  '/_dashboard/messages': typeof DashboardMessagesRoute
  '/_dashboard/monitoring': typeof DashboardMonitoringRoute
  '/_dashboard/queues': typeof DashboardQueuesRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/roles': typeof DashboardRolesRoute
  '/_dashboard/routing': typeof DashboardRoutingRoute
  '/_dashboard/senders': typeof DashboardSendersRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/smpp-server': typeof DashboardSmppServerRoute
  '/_dashboard/swagger': typeof DashboardSwaggerRoute
  '/_dashboard/tenants': typeof DashboardTenantsRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/ussd': typeof DashboardUssdRouteWithChildren
  '/_dashboard/webhooks': typeof DashboardWebhooksRoute
  '/account/login': typeof AccountLoginRoute
  '/_dashboard/administration/roles': typeof DashboardAdministrationRolesRoute
  '/_dashboard/administration/tenants': typeof DashboardAdministrationTenantsRoute
  '/_dashboard/administration/users': typeof DashboardAdministrationUsersRoute
  '/_dashboard/developers/api-keys': typeof DashboardDevelopersApiKeysRoute
  '/_dashboard/developers/documentation': typeof DashboardDevelopersDocumentationRoute
  '/_dashboard/developers/logs': typeof DashboardDevelopersLogsRoute
  '/_dashboard/developers/webhooks': typeof DashboardDevelopersWebhooksRoute
  '/_dashboard/network/carriers': typeof DashboardNetworkCarriersRoute
  '/_dashboard/network/connections': typeof DashboardNetworkConnectionsRoute
  '/_dashboard/network/queues': typeof DashboardNetworkQueuesRoute
  '/_dashboard/network/routing': typeof DashboardNetworkRoutingRoute
  '/_dashboard/network/smpp-server': typeof DashboardNetworkSmppServerRoute
  '/_dashboard/operations/alarms': typeof DashboardOperationsAlarmsRoute
  '/_dashboard/operations/monitoring': typeof DashboardOperationsMonitoringRoute
  '/_dashboard/traffic/delivery-reports': typeof DashboardTrafficDeliveryReportsRoute
  '/_dashboard/traffic/inbound-mo': typeof DashboardTrafficInboundMoRoute
  '/_dashboard/traffic/logs': typeof DashboardTrafficLogsRoute
  '/_dashboard/traffic/reports-billing': typeof DashboardTrafficReportsBillingRoute
  '/_dashboard/traffic/sender-ids': typeof DashboardTrafficSenderIdsRoute
  '/_dashboard/traffic/ussd-sessions': typeof DashboardTrafficUssdSessionsRoute
  '/_dashboard/ussd/notify': typeof DashboardUssdNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/alerts'
    | '/api-keys'
    | '/audit'
    | '/audit-logs'
    | '/carriers'
    | '/connections'
    | '/dashboard'
    | '/delivery-reports'
    | '/inbound'
    | '/messages'
    | '/monitoring'
    | '/queues'
    | '/reports'
    | '/roles'
    | '/routing'
    | '/senders'
    | '/settings'
    | '/smpp-server'
    | '/swagger'
    | '/tenants'
    | '/users'
    | '/ussd'
    | '/webhooks'
    | '/account/login'
    | '/administration/roles'
    | '/administration/tenants'
    | '/administration/users'
    | '/developers/api-keys'
    | '/developers/documentation'
    | '/developers/logs'
    | '/developers/webhooks'
    | '/network/carriers'
    | '/network/connections'
    | '/network/queues'
    | '/network/routing'
    | '/network/smpp-server'
    | '/operations/alarms'
    | '/operations/monitoring'
    | '/traffic/delivery-reports'
    | '/traffic/inbound-mo'
    | '/traffic/logs'
    | '/traffic/reports-billing'
    | '/traffic/sender-ids'
    | '/traffic/ussd-sessions'
    | '/ussd/notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/alerts'
    | '/api-keys'
    | '/audit'
    | '/audit-logs'
    | '/carriers'
    | '/connections'
    | '/dashboard'
    | '/delivery-reports'
    | '/inbound'
    | '/messages'
    | '/monitoring'
    | '/queues'
    | '/reports'
    | '/roles'
    | '/routing'
    | '/senders'
    | '/settings'
    | '/smpp-server'
    | '/swagger'
    | '/tenants'
    | '/users'
    | '/ussd'
    | '/webhooks'
    | '/account/login'
    | '/administration/roles'
    | '/administration/tenants'
    | '/administration/users'
    | '/developers/api-keys'
    | '/developers/documentation'
    | '/developers/logs'
    | '/developers/webhooks'
    | '/network/carriers'
    | '/network/connections'
    | '/network/queues'
    | '/network/routing'
    | '/network/smpp-server'
    | '/operations/alarms'
    | '/operations/monitoring'
    | '/traffic/delivery-reports'
    | '/traffic/inbound-mo'
    | '/traffic/logs'
    | '/traffic/reports-billing'
    | '/traffic/sender-ids'
    | '/traffic/ussd-sessions'
    | '/ussd/notify'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/logout'
    | '/register'
    | '/_dashboard/alerts'
    | '/_dashboard/api-keys'
    | '/_dashboard/audit'
    | '/_dashboard/audit-logs'
    | '/_dashboard/carriers'
    | '/_dashboard/connections'
    | '/_dashboard/dashboard'
    | '/_dashboard/delivery-reports'
    | '/_dashboard/inbound'
    | '/_dashboard/messages'
    | '/_dashboard/monitoring'
    | '/_dashboard/queues'
    | '/_dashboard/reports'
    | '/_dashboard/roles'
    | '/_dashboard/routing'
    | '/_dashboard/senders'
    | '/_dashboard/settings'
    | '/_dashboard/smpp-server'
    | '/_dashboard/swagger'
    | '/_dashboard/tenants'
    | '/_dashboard/users'
    | '/_dashboard/ussd'
    | '/_dashboard/webhooks'
    | '/account/login'
    | '/_dashboard/administration/roles'
    | '/_dashboard/administration/tenants'
    | '/_dashboard/administration/users'
    | '/_dashboard/developers/api-keys'
    | '/_dashboard/developers/documentation'
    | '/_dashboard/developers/logs'
    | '/_dashboard/developers/webhooks'
    | '/_dashboard/network/carriers'
    | '/_dashboard/network/connections'
    | '/_dashboard/network/queues'
    | '/_dashboard/network/routing'
    | '/_dashboard/network/smpp-server'
    | '/_dashboard/operations/alarms'
    | '/_dashboard/operations/monitoring'
    | '/_dashboard/traffic/delivery-reports'
    | '/_dashboard/traffic/inbound-mo'
    | '/_dashboard/traffic/logs'
    | '/_dashboard/traffic/reports-billing'
    | '/_dashboard/traffic/sender-ids'
    | '/_dashboard/traffic/ussd-sessions'
    | '/_dashboard/ussd/notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  AccountLoginRoute: typeof AccountLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/alerts': {
      id: '/_dashboard/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/api-keys': {
      id: '/_dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/audit': {
      id: '/_dashboard/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/audit-logs': {
      id: '/_dashboard/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/carriers': {
      id: '/_dashboard/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof DashboardCarriersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/connections': {
      id: '/_dashboard/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof DashboardConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/delivery-reports': {
      id: '/_dashboard/delivery-reports'
      path: '/delivery-reports'
      fullPath: '/delivery-reports'
      preLoaderRoute: typeof DashboardDeliveryReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inbound': {
      id: '/_dashboard/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof DashboardInboundRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/messages': {
      id: '/_dashboard/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/monitoring': {
      id: '/_dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/queues': {
      id: '/_dashboard/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof DashboardQueuesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/roles': {
      id: '/_dashboard/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/routing': {
      id: '/_dashboard/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof DashboardRoutingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/senders': {
      id: '/_dashboard/senders'
      path: '/senders'
      fullPath: '/senders'
      preLoaderRoute: typeof DashboardSendersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/smpp-server': {
      id: '/_dashboard/smpp-server'
      path: '/smpp-server'
      fullPath: '/smpp-server'
      preLoaderRoute: typeof DashboardSmppServerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/swagger': {
      id: '/_dashboard/swagger'
      path: '/swagger'
      fullPath: '/swagger'
      preLoaderRoute: typeof DashboardSwaggerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tenants': {
      id: '/_dashboard/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof DashboardTenantsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ussd': {
      id: '/_dashboard/ussd'
      path: '/ussd'
      fullPath: '/ussd'
      preLoaderRoute: typeof DashboardUssdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/webhooks': {
      id: '/_dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/administration/roles': {
      id: '/_dashboard/administration/roles'
      path: '/administration/roles'
      fullPath: '/administration/roles'
      preLoaderRoute: typeof DashboardAdministrationRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/administration/tenants': {
      id: '/_dashboard/administration/tenants'
      path: '/administration/tenants'
      fullPath: '/administration/tenants'
      preLoaderRoute: typeof DashboardAdministrationTenantsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/administration/users': {
      id: '/_dashboard/administration/users'
      path: '/administration/users'
      fullPath: '/administration/users'
      preLoaderRoute: typeof DashboardAdministrationUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/developers/api-keys': {
      id: '/_dashboard/developers/api-keys'
      path: '/developers/api-keys'
      fullPath: '/developers/api-keys'
      preLoaderRoute: typeof DashboardDevelopersApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/developers/documentation': {
      id: '/_dashboard/developers/documentation'
      path: '/developers/documentation'
      fullPath: '/developers/documentation'
      preLoaderRoute: typeof DashboardDevelopersDocumentationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/developers/logs': {
      id: '/_dashboard/developers/logs'
      path: '/developers/logs'
      fullPath: '/developers/logs'
      preLoaderRoute: typeof DashboardDevelopersLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/developers/webhooks': {
      id: '/_dashboard/developers/webhooks'
      path: '/developers/webhooks'
      fullPath: '/developers/webhooks'
      preLoaderRoute: typeof DashboardDevelopersWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/network/carriers': {
      id: '/_dashboard/network/carriers'
      path: '/network/carriers'
      fullPath: '/network/carriers'
      preLoaderRoute: typeof DashboardNetworkCarriersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/network/connections': {
      id: '/_dashboard/network/connections'
      path: '/network/connections'
      fullPath: '/network/connections'
      preLoaderRoute: typeof DashboardNetworkConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/network/queues': {
      id: '/_dashboard/network/queues'
      path: '/network/queues'
      fullPath: '/network/queues'
      preLoaderRoute: typeof DashboardNetworkQueuesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/network/routing': {
      id: '/_dashboard/network/routing'
      path: '/network/routing'
      fullPath: '/network/routing'
      preLoaderRoute: typeof DashboardNetworkRoutingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/network/smpp-server': {
      id: '/_dashboard/network/smpp-server'
      path: '/network/smpp-server'
      fullPath: '/network/smpp-server'
      preLoaderRoute: typeof DashboardNetworkSmppServerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/operations/alarms': {
      id: '/_dashboard/operations/alarms'
      path: '/operations/alarms'
      fullPath: '/operations/alarms'
      preLoaderRoute: typeof DashboardOperationsAlarmsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/operations/monitoring': {
      id: '/_dashboard/operations/monitoring'
      path: '/operations/monitoring'
      fullPath: '/operations/monitoring'
      preLoaderRoute: typeof DashboardOperationsMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/traffic/delivery-reports': {
      id: '/_dashboard/traffic/delivery-reports'
      path: '/traffic/delivery-reports'
      fullPath: '/traffic/delivery-reports'
      preLoaderRoute: typeof DashboardTrafficDeliveryReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/traffic/inbound-mo': {
      id: '/_dashboard/traffic/inbound-mo'
      path: '/traffic/inbound-mo'
      fullPath: '/traffic/inbound-mo'
      preLoaderRoute: typeof DashboardTrafficInboundMoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/traffic/logs': {
      id: '/_dashboard/traffic/logs'
      path: '/traffic/logs'
      fullPath: '/traffic/logs'
      preLoaderRoute: typeof DashboardTrafficLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/traffic/reports-billing': {
      id: '/_dashboard/traffic/reports-billing'
      path: '/traffic/reports-billing'
      fullPath: '/traffic/reports-billing'
      preLoaderRoute: typeof DashboardTrafficReportsBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/traffic/sender-ids': {
      id: '/_dashboard/traffic/sender-ids'
      path: '/traffic/sender-ids'
      fullPath: '/traffic/sender-ids'
      preLoaderRoute: typeof DashboardTrafficSenderIdsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/traffic/ussd-sessions': {
      id: '/_dashboard/traffic/ussd-sessions'
      path: '/traffic/ussd-sessions'
      fullPath: '/traffic/ussd-sessions'
      preLoaderRoute: typeof DashboardTrafficUssdSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ussd/notify': {
      id: '/_dashboard/ussd/notify'
      path: '/notify'
      fullPath: '/ussd/notify'
      preLoaderRoute: typeof DashboardUssdNotifyRouteImport
      parentRoute: typeof DashboardUssdRoute
    }
  }
}

interface DashboardUssdRouteChildren {
  DashboardUssdNotifyRoute: typeof DashboardUssdNotifyRoute
}

const DashboardUssdRouteChildren: DashboardUssdRouteChildren = {
  DashboardUssdNotifyRoute: DashboardUssdNotifyRoute,
}

const DashboardUssdRouteWithChildren = DashboardUssdRoute._addFileChildren(
  DashboardUssdRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardAuditLogsRoute: typeof DashboardAuditLogsRoute
  DashboardCarriersRoute: typeof DashboardCarriersRoute
  DashboardConnectionsRoute: typeof DashboardConnectionsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDeliveryReportsRoute: typeof DashboardDeliveryReportsRoute
  DashboardInboundRoute: typeof DashboardInboundRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardQueuesRoute: typeof DashboardQueuesRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardRoutingRoute: typeof DashboardRoutingRoute
  DashboardSendersRoute: typeof DashboardSendersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSmppServerRoute: typeof DashboardSmppServerRoute
  DashboardSwaggerRoute: typeof DashboardSwaggerRoute
  DashboardTenantsRoute: typeof DashboardTenantsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardUssdRoute: typeof DashboardUssdRouteWithChildren
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  DashboardAdministrationRolesRoute: typeof DashboardAdministrationRolesRoute
  DashboardAdministrationTenantsRoute: typeof DashboardAdministrationTenantsRoute
  DashboardAdministrationUsersRoute: typeof DashboardAdministrationUsersRoute
  DashboardDevelopersApiKeysRoute: typeof DashboardDevelopersApiKeysRoute
  DashboardDevelopersDocumentationRoute: typeof DashboardDevelopersDocumentationRoute
  DashboardDevelopersLogsRoute: typeof DashboardDevelopersLogsRoute
  DashboardDevelopersWebhooksRoute: typeof DashboardDevelopersWebhooksRoute
  DashboardNetworkCarriersRoute: typeof DashboardNetworkCarriersRoute
  DashboardNetworkConnectionsRoute: typeof DashboardNetworkConnectionsRoute
  DashboardNetworkQueuesRoute: typeof DashboardNetworkQueuesRoute
  DashboardNetworkRoutingRoute: typeof DashboardNetworkRoutingRoute
  DashboardNetworkSmppServerRoute: typeof DashboardNetworkSmppServerRoute
  DashboardOperationsAlarmsRoute: typeof DashboardOperationsAlarmsRoute
  DashboardOperationsMonitoringRoute: typeof DashboardOperationsMonitoringRoute
  DashboardTrafficDeliveryReportsRoute: typeof DashboardTrafficDeliveryReportsRoute
  DashboardTrafficInboundMoRoute: typeof DashboardTrafficInboundMoRoute
  DashboardTrafficLogsRoute: typeof DashboardTrafficLogsRoute
  DashboardTrafficReportsBillingRoute: typeof DashboardTrafficReportsBillingRoute
  DashboardTrafficSenderIdsRoute: typeof DashboardTrafficSenderIdsRoute
  DashboardTrafficUssdSessionsRoute: typeof DashboardTrafficUssdSessionsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardAuditLogsRoute: DashboardAuditLogsRoute,
  DashboardCarriersRoute: DashboardCarriersRoute,
  DashboardConnectionsRoute: DashboardConnectionsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDeliveryReportsRoute: DashboardDeliveryReportsRoute,
  DashboardInboundRoute: DashboardInboundRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardQueuesRoute: DashboardQueuesRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardRoutingRoute: DashboardRoutingRoute,
  DashboardSendersRoute: DashboardSendersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSmppServerRoute: DashboardSmppServerRoute,
  DashboardSwaggerRoute: DashboardSwaggerRoute,
  DashboardTenantsRoute: DashboardTenantsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardUssdRoute: DashboardUssdRouteWithChildren,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardAdministrationRolesRoute: DashboardAdministrationRolesRoute,
  DashboardAdministrationTenantsRoute: DashboardAdministrationTenantsRoute,
  DashboardAdministrationUsersRoute: DashboardAdministrationUsersRoute,
  DashboardDevelopersApiKeysRoute: DashboardDevelopersApiKeysRoute,
  DashboardDevelopersDocumentationRoute: DashboardDevelopersDocumentationRoute,
  DashboardDevelopersLogsRoute: DashboardDevelopersLogsRoute,
  DashboardDevelopersWebhooksRoute: DashboardDevelopersWebhooksRoute,
  DashboardNetworkCarriersRoute: DashboardNetworkCarriersRoute,
  DashboardNetworkConnectionsRoute: DashboardNetworkConnectionsRoute,
  DashboardNetworkQueuesRoute: DashboardNetworkQueuesRoute,
  DashboardNetworkRoutingRoute: DashboardNetworkRoutingRoute,
  DashboardNetworkSmppServerRoute: DashboardNetworkSmppServerRoute,
  DashboardOperationsAlarmsRoute: DashboardOperationsAlarmsRoute,
  DashboardOperationsMonitoringRoute: DashboardOperationsMonitoringRoute,
  DashboardTrafficDeliveryReportsRoute: DashboardTrafficDeliveryReportsRoute,
  DashboardTrafficInboundMoRoute: DashboardTrafficInboundMoRoute,
  DashboardTrafficLogsRoute: DashboardTrafficLogsRoute,
  DashboardTrafficReportsBillingRoute: DashboardTrafficReportsBillingRoute,
  DashboardTrafficSenderIdsRoute: DashboardTrafficSenderIdsRoute,
  DashboardTrafficUssdSessionsRoute: DashboardTrafficUssdSessionsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  AccountLoginRoute: AccountLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
