import type { PermissionCategory, RoleItem } from "./types"

export const PERMISSION_CATEGORIES: PermissionCategory[] = [
  {
    name: "Administration",
    permissions: [
      { key: "tenants.read", label: "Read Tenants" },
      { key: "tenants.manage", label: "Manage Tenants" },
      { key: "users.read", label: "Read Users" },
      { key: "users.manage", label: "Manage Users" },
      { key: "roles.manage", label: "Manage Roles" },
      { key: "settings.manage", label: "Manage Settings" },
    ],
  },
  {
    name: "Billing",
    permissions: [
      { key: "billing.read", label: "Read Billing" },
      { key: "billing.manage", label: "Manage Billing" },
    ],
  },
  {
    name: "Campaigns",
    permissions: [
      { key: "campaigns.read", label: "Read Campaigns" },
      { key: "campaigns.create", label: "Create Campaigns" },
      { key: "campaigns.send", label: "Send Campaigns" },
    ],
  },
  {
    name: "Dashboard",
    permissions: [
      { key: "dashboard.read", label: "View Dashboard" },
    ],
  },
  {
    name: "Developers",
    permissions: [
      { key: "webhooks.read", label: "Read Webhooks" },
      { key: "webhooks.manage", label: "Manage Webhooks" },
      { key: "apikeys.read", label: "Read API Keys" },
      { key: "apikeys.manage", label: "Manage API Keys" },
      { key: "apilogs.read", label: "Read API Logs" },
    ],
  },
  {
    name: "Messaging",
    permissions: [
      { key: "messages.read", label: "Read Messages" },
      { key: "messages.send", label: "Send Messages" },
      { key: "messages.cancel", label: "Cancel Messages" },
      { key: "senders.read", label: "Read Sender IDs" },
      { key: "senders.manage", label: "Manage Sender IDs" },
      { key: "contacts.read", label: "Read Contacts" },
      { key: "contacts.manage", label: "Manage Contacts" },
      { key: "templates.read", label: "Read Templates" },
      { key: "templates.manage", label: "Manage Templates" },
    ],
  },
  {
    name: "Network",
    permissions: [
      { key: "carriers.read", label: "Read Carriers" },
      { key: "carriers.manage", label: "Manage Carriers" },
      { key: "routing.read", label: "Read Routing" },
      { key: "routing.manage", label: "Manage Routing" },
    ],
  },
  {
    name: "Operations",
    permissions: [
      { key: "monitoring.read", label: "Read Monitoring" },
      { key: "alerts.read", label: "Read Alerts" },
      { key: "alerts.manage", label: "Manage Alerts" },
      { key: "audit.read", label: "Read Audit Log" },
    ],
  },
  {
    name: "Reports",
    permissions: [
      { key: "reports.read", label: "Read Reports" },
    ],
  },
  {
    name: "USSD",
    permissions: [
      { key: "ussd.read", label: "Read USSD" },
      { key: "ussd.send", label: "Send USSD" },
    ],
  },
]

// All 37 permission keys
export const ALL_PERMISSION_KEYS = PERMISSION_CATEGORIES.flatMap((c) =>
  c.permissions.map((p) => p.key)
)

export const INITIAL_ROLES: RoleItem[] = [
  {
    id: "developer",
    name: "Developer",
    isSystem: true,
    description: "API keys, webhooks, and integration access",
    permissions: [
      "dashboard.read",
      "webhooks.read",
      "webhooks.manage",
      "apikeys.read",
      "apikeys.manage",
      "apilogs.read",
      "messages.read",
      "messages.send",
      "senders.read",
      "contacts.read",
      "templates.read",
      "ussd.read",
      "ussd.send",
    ],
    usersCount: 0,
  },
  {
    id: "finance",
    name: "Finance",
    isSystem: true,
    description: "Billing, wallets, and financial reporting",
    permissions: [
      "dashboard.read",
      "billing.read",
      "billing.manage",
      "reports.read",
      "messages.read",
      "audit.read",
    ],
    usersCount: 0,
  },
  {
    id: "gateway-admin",
    name: "Gateway Admin",
    isSystem: true,
    description: "Administer gateway configuration and operations",
    permissions: [...ALL_PERMISSION_KEYS],
    usersCount: 0,
  },
  {
    id: "operations",
    name: "Operations",
    isSystem: true,
    description: "Day-to-day messaging and carrier operations",
    permissions: [
      "dashboard.read",
      "messages.read",
      "messages.send",
      "messages.cancel",
      "senders.read",
      "senders.manage",
      "contacts.read",
      "templates.read",
      "carriers.read",
      "carriers.manage",
      "routing.read",
      "routing.manage",
      "monitoring.read",
      "alerts.read",
      "alerts.manage",
      "audit.read",
      "reports.read",
      "ussd.read",
      "ussd.send",
      "apilogs.read",
      "users.read",
      "tenants.read",
      "campaigns.read",
    ],
    usersCount: 0,
  },
  {
    id: "read-only",
    name: "Read Only",
    isSystem: true,
    description: "Read-only access to assigned resources",
    permissions: [
      "dashboard.read",
      "tenants.read",
      "users.read",
      "billing.read",
      "campaigns.read",
      "webhooks.read",
      "apikeys.read",
      "apilogs.read",
      "messages.read",
      "senders.read",
      "contacts.read",
      "templates.read",
      "carriers.read",
      "routing.read",
      "reports.read",
    ],
    usersCount: 0,
  },
  {
    id: "super-admin",
    name: "Super Admin",
    isSystem: true,
    description: "Full platform access across all tenants",
    permissions: [],
    usersCount: 1,
  },
  {
    id: "support",
    name: "Support",
    isSystem: true,
    description: "Customer support with limited write access",
    permissions: [
      "dashboard.read",
      "users.read",
      "messages.read",
      "senders.read",
      "contacts.read",
      "templates.read",
      "alerts.read",
      "apilogs.read",
    ],
    usersCount: 0,
  },
  {
    id: "tenant-admin",
    name: "Tenant Admin",
    isSystem: true,
    description: "Administer a single tenant account",
    permissions: [
      "dashboard.read",
      "users.read",
      "users.manage",
      "roles.manage",
      "settings.manage",
      "billing.read",
      "campaigns.read",
      "campaigns.create",
      "campaigns.send",
      "webhooks.read",
      "webhooks.manage",
      "apikeys.read",
      "apikeys.manage",
      "apilogs.read",
      "messages.read",
      "messages.send",
      "messages.cancel",
      "senders.read",
      "senders.manage",
      "contacts.read",
      "contacts.manage",
      "templates.read",
      "templates.manage",
    ],
    usersCount: 0,
  },
  {
    id: "tenant-user",
    name: "Tenant User",
    isSystem: true,
    description: "Standard tenant messaging user",
    permissions: [
      "dashboard.read",
      "campaigns.read",
      "campaigns.create",
      "campaigns.send",
      "messages.read",
      "messages.send",
      "senders.read",
      "contacts.read",
      "contacts.manage",
      "templates.read",
      "templates.manage",
      "ussd.read",
    ],
    usersCount: 0,
  },
]
